//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Gmud32.RC
//
#define IDR_MudTYPE_SRVR_IP             4
#define IDR_MudTYPE_SRVR_EMB            5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_MudTYPE                     129
#define IDD_VIEW_SETTINGS               130
#define IDD_CONNECT                     131
#define IDD_RENAME                      132
#define IDD_MACRO_BAR                   133
#define IDD_BUTTON_EDIT                 134
#define IDD_TRIGGER_DIALOG              135
#define IDD_TEXT_COLOR                  136
#define IDD_CONNECTED_WORLD_BAR         138
#define IDB_BITMAP1                     138
#define IDD_SOUNDS_DIALOG               140
#define IDD_NAME_DIALOG                 142
#define IDD_SELARRAY_EDIT               143
#define IDD_REPLACE_FILE                144
#define IDD_ALIAS_EDIT                  145
#define IDD_ALIAS_SINGLE_EDIT           146
#define IDD_DIALOG1                     147
#define IDC_80columns                   1000
#define IDC_wrapscreen                  1001
#define IDC_wordwrap                    1004
#define IDC_characterwrap               1005
#define IDC_WORLDLIST                   1006
#define IDC_HOSTNAME                    1007
#define IDC_PORT                        1008
#define IDC_CONNECTSTRING               1009
#define IDC_ADD                         1010
#define IDC_DELETE_WORLD                1011
#define IDC_RENAME_WORLD                1012
#define IDC_NEWNAME                     1013
#define IDC_OLDNAME                     1014
#define IDC_BUTTON1                     1015
#define IDC_BUTTON2                     1016
#define IDC_BUTTON3                     1017
#define IDC_BUTTON4                     1018
#define IDC_BUTTON5                     1019
#define IDC_BUTTON6                     1020
#define IDC_BUTTON7                     1021
#define IDC_BUTTON8                     1022
#define IDC_BUTTON9                     1023
#define IDC_BUTTON10                    1024
#define IDC_EDIT                        1025
#define IDC_BUTTON_EDIT                 1025
#define IDC_EDIT1                       1026
#define IDC_EDIT4                       1029
#define IDC_TRIGGER_LIST                1029
#define IDC_EDIT5                       1030
#define IDC_EDIT2                       1031
#define IDC_EDIT6                       1032
#define IDC_MUDTEXT                     1032
#define IDC_EDIT3                       1033
#define IDC_EDIT7                       1034
#define IDC_PLAYFILE                    1034
#define IDC_EDIT8                       1035
#define IDC_BROWSE_FILE                 1035
#define IDC_EDIT9                       1036
#define IDC_DELETE                      1036
#define IDC_EDIT10                      1037
#define IDC_FILENAME                    1037
#define IDADD                           1038
#define IDC_TEST_SOUND                  1039
#define IDC_CHANGE_FOREGROUND_COLOR     1040
#define IDC_CHANGE_BACKGROUND_COLOR     1041
#define IDC_SHOW_BACKGROUND             1042
#define IDC_SHOW_FOREGROUND             1043
#define IDC_COMBO1                      1045
#define IDC_COMBO2                      1046
#define IDC_CONNECT_LIST                1046
#define IDC_CHECK1                      1047
#define IDC_BELL_SOUND                  1048
#define IDC_TRIGGER_SOUND               1049
#define IDC_CONNECT_BEEP                1050
#define IDC_ENABLE_ANSI                 1051
#define IDC_PROMPT                      1052
#define IDC_NAME                        1053
#define IDC_ARRAY_LIST                  1055
#define IDC_NEW                         1056
#define IDC_COPY                        1057
#define IDC_TRIGSETNAME                 1059
#define IDC_CHANGE_MACRO                1060
#define IDC_CHANGE_TRIGGER              1061
#define IDC_MACROSETNAME                1062
#define IDC_DESCRIPTION                 1063
#define IDC_CHANGE_ALIAS                1064
#define IDC_APPEND                      1065
#define IDC_INSERT                      1066
#define IDC_ALIAS_LIST                  1067
#define IDC_ALIAS_OUTPUT                1068
#define IDC_ALIAS_SET                   1069
#define IDC_OUTPUT                      1070
#define IDC_INPUT                       1071
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_SERVER_CONNECT               32771
#define ID_SERVER_DISCONNECT            32772
#define ID_VIEW_WRAP                    32773
#define ID_WINDOW_NEW_OPEN_DOC          32776
#define ID_FILE_EDITWORLDLIST           32777
#define ID_VIEW_FONT                    32778
#define ID_FILE_EDITTRIGGERLIST         32780
#define ID_WINDOW_COLOR                 32781
#define ID_SOUNDS_SETTINGS              32783
#define ID_WINDOW_PAUSE                 32784
#define ID_FILE_TOGGLELOGGING           32785
#define ID_FILE_TOGGLELOCALECHOING      32786
#define ID_PASTE_FILE                   32787
#define ID_EDIT_ALIASLIST               32788
#define ID_VIEW_MACROWINDOW             0xE830
#define ID_VIEW_WORLDWINDOW             0xE831

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
